language: node_js
node_js:
  - "8"
cache:
  directories:
    - "node_modules"
script:
  - npm test
  - npm run prod
before_deploy:
  - cd ./dist
deploy:
  provider: heroku
  skip-cleanup: true
  api_key:
    secure: $HEROKU_TOKEN
  app: pluralsight-redux-saga
  on:
    repo: Darmaiad/pluralsight-redux-saga